// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmIV46VieLHbbQP3_NzI-Hs9gkAy3taI',
    appId: '1:565391630059:web:6c71ae58528293e06068ae',
    messagingSenderId: '565391630059',
    projectId: 'horario-siga',
    authDomain: 'horario-siga.firebaseapp.com',
    storageBucket: 'horario-siga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPrlwtUJopir0zIRaCZwOg288AybdPIQ',
    appId: '1:565391630059:android:9db805276756a6956068ae',
    messagingSenderId: '565391630059',
    projectId: 'horario-siga',
    storageBucket: 'horario-siga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7F_gyek_-FA3Qcq6b8tU9eNXNHKBXHg',
    appId: '1:565391630059:ios:4f1cd8a213ecd6236068ae',
    messagingSenderId: '565391630059',
    projectId: 'horario-siga',
    storageBucket: 'horario-siga.firebasestorage.app',
    iosBundleId: 'com.example.grupoArchivosSiga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW7F_gyek_-FA3Qcq6b8tU9eNXNHKBXHg',
    appId: '1:565391630059:ios:4f1cd8a213ecd6236068ae',
    messagingSenderId: '565391630059',
    projectId: 'horario-siga',
    storageBucket: 'horario-siga.firebasestorage.app',
    iosBundleId: 'com.example.grupoArchivosSiga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWmIV46VieLHbbQP3_NzI-Hs9gkAy3taI',
    appId: '1:565391630059:web:07ddd3b0cce87f576068ae',
    messagingSenderId: '565391630059',
    projectId: 'horario-siga',
    authDomain: 'horario-siga.firebaseapp.com',
    storageBucket: 'horario-siga.firebasestorage.app',
  );
}
